### ISSUE TITLE
Multiple radio groups with overlapping option values on the same page breaks the groups except the first

### ISSUE THREAD

**Issue by JvJefke** [digipolisantwerp/antwerp-ui_react#179]
## Describe the bug

It is impossible to have multiple radio groups within the same page of which values overlap. This happens because the id of the radio input corresponds with the value. This means that you can only have 1 radio button with a specific value per page. 

## To Reproduce

1. Add 2 radio groups with the same options within a page
2. Click on a radio button of the second radio group
3. The value of the first radio group has been set instead of the second one

## Expected behavior

The value of the second radio button should have been set. 

## OS (please complete the following information):

 - Device: Macbook Pro
 - OS: macOs Catalina
 - Browser: Chrome
 - Version: 86.0.4240.198

## Additional context

I think the ids should not be equal to the value but to something like this `${fieldGroupName}_${value}`

**Comment by TriangleJuice** [comment]
Closing this issue as it was already fixed.
