### ISSUE TITLE
Calendar component, the day of the week is off by one.

### ISSUE THREAD

**Issue by mantebridts** [digipolisantwerp/antwerp-ui_react#186]
## The bug

When using the Calendar component, the selected day of the week is off by one.

## To Reproduce

1. Go to [https://digipolisantwerp.github.io/acpaas-ui_react/#datepicker](https://digipolisantwerp.github.io/acpaas-ui_react/#datepicker)
2. Inspect the dates in the calendar-view
3. Notice the day of the week is off by one. Today is December 1st, a Tuesday. In the calendar, this is shown as a Monday.

## Expected behaviour

The calendar should display the correct day of the week.

## Screenshots

![Screenshot 2020-12-01 at 14 16 05](https://user-images.githubusercontent.com/1894451/100745628-db020b80-33df-11eb-87b4-5965c9bbe673.png)

## OS:

 - Device: Apple Macbook
 - OS: macOS Catalina
 - Browser: Firefox
 - Version: 83.0

## Additional context

I am currently viewing the Calendar component in CET, Timezone GMT+1.

**Comment by TriangleJuice** [comment]
Closing this issue as it was already fixed.
