### ISSUE TITLE
React scripts dependency causing dependency tree issues

### ISSUE THREAD

**Issue by maartenraes** [digipolisantwerp/antwerp-ui_react#187]
## Describe the bug

Updating from acpaas-ui_react `2.4.1` to `4.8.1` causes a dependency tree conflict with `react-scripts` newest version (4.0.0) 

## To Reproduce

1. Pull project `notif_admin_ui_app_nodejs` from Bitbucket
2. Update version `@acpaas-ui/react-components` to `4.8.1`
3. Run `yarn && yarn dev`

## Expected behavior

@acpaas-ui/react-components shouldn't have react-scripts as dependency, or if it needs to, the version should be updated to latest.

## Screenshots
![image](https://user-images.githubusercontent.com/26487384/101361360-295f5080-389f-11eb-8468-ca7c086c7e08.png)

## OS (please complete the following information):

 - Device: Desktop
 - OS: Win10
 - Browser: N/A
 - Version N/A

## Additional context

The error mentions babel-jest, this is a dependency from react-scripts, due to having both 3.4.3 and 4.0.0 version of react-scripts the babel-jest errors.

**Comment by hstandaert** [comment]
I'm also experiencing this issue. Is there any particular reason `react-scripts` is a dependency? Looking at `package.json`, it is not used anywhere.

**Comment by TriangleJuice** [comment]
Closing this issue as it was already fixed.
