### ISSUE TITLE
Datepicker errordescription

### ISSUE THREAD

**Issue by maartenraes** [digipolisantwerp/antwerp-ui_react#235]
## Is your feature request related to a problem? Please describe.

Datepicker component has a state field just like the other form inputs. 
However when using it to to show validation error with the error-state of the input it doesn't color red. 

## Describe the solution you'd like

Color the description red when `state="error"`

## Describe alternatives you've considered

Naming should be the same everywhere to keep it consistent, Datepicker has description, Textfield has errorDescription. 
Preferably all form input would have description and errorDescription and support both use cases this way.

**Comment by TriangleJuice** [comment]
This was added in v6.4.0
