### ISSUE TITLE
Support for `description` in Select component

### ISSUE THREAD

**Issue by hstandaert** [digipolisantwerp/antwerp-ui_react#237]
## Is your feature request related to a problem? Please describe.

No support for `description` prop in `Select` component

## Describe the solution you'd like

```js
<Select 
  description="A description displayed underneath the field"
  {...props}
/>
```

<img width="631" alt="Screenshot 2021-04-20 at 10 17 32" src="https://user-images.githubusercontent.com/4415097/115362244-9fff4980-a1c1-11eb-9647-4c537ba63631.png">

**Comment by TriangleJuice** [comment]
This was added in v6.4.0
