### ISSUE TITLE
Datepciker headers are incorrect when using locale (en)

### ISSUE THREAD

**Issue by JorneDelforge** [digipolisantwerp/antwerp-ui_react#246]
## Describe the bug

When using the react date picker in 'en' locale, the headers are misaligned. Sunday is first day of the week, but the calendar dates are still assuming Monday as first day of the week.

Screenshot attached.

## To Reproduce

1. Go to https://digipolisantwerp.github.io/antwerp-ui_react/#form ==> date picker component, make certain locale is set to 'en' in the example code
2. Open the date picker and compare it to you system calendar. Day of week does not match the actual dates. Example: 1 august 2021 is a Sunday, not a Saturday

## Screenshots

<img width="404" alt="Screenshot 2021-08-04 at 12 55 30" src="https://user-images.githubusercontent.com/6309415/128349626-1bb746d4-90df-4bc4-bf6c-e7c97bfc667b.png">

## OS (please complete the following information):

 - Device: MacBook
 - OS: OS X
 - Browser Safari & Chrome

## Additional context

Has been discussed with Joeri S. When setting locale to 'nl' the issue is fixed.

**Comment by jsebrech** [comment]
There is an additional issue. When starting a fresh project with the Digipolis Starter kit, and including the Datepicker component on a page, locale=nl does not work. This is related to https://github.com/moment/moment/issues/4216

As a workaround, one can put this code at the top of index.js:
`import 'moment/locale/nl';`
