### ISSUE TITLE
Datepicker placeholder ondersteuning

### ISSUE THREAD

**Issue by JvJefke** [digipolisantwerp/antwerp-ui_react#276]
## Is your feature request related to a problem? Please describe.

We cannot currently add a placeholder to a datepicker component.
Is it possible to add support for this?

## Describe the solution you'd like

I'd like to be able to add a placeholder prop to the datepicker component:
```
<Datepicker
    ...otherProps
    placeholder="a-placeholder"
 />
```

**Comment by TriangleJuice** [comment]
This was added in v6.4.0
